// Auto-generated by LibreLane
module u_s_r(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[1:0] mode,
  input[3:0] D,
  input S_in,
  output[3:0] Q
);
endmodule
